name: authentication_repository
description: Good Wallet's Authentication Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  firebase_auth: ^4.9.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
