name: good_wallet
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: package/authentication_repository
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  sliding_up_panel: ^2.0.0+1
  transaction_repository:
    path: package/transaction_repository
  wallet_ui:
    path: package/wallet_ui
  wallet_widget:
    path: package/wallet_widget

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/empty_placeholder/
    - assets/logo/
  fonts:
    - family: AnonymousPro
      fonts:
        - asset: assets/fonts/AnonymousPro-Regular.ttf
        - asset: assets/fonts/AnonymousPro-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
